/**
 * Content Sync & Homepage Generator
 * ═══════════════════════════════════
 * 1. Syncs publish:true notes from Obsidian vault → Quartz content/
 * 2. Auto-generates a beautiful index.md homepage with:
 *    - Hero section
 *    - Featured (latest) report card with excerpt
 *    - Category grid with counts
 *    - Recent reports timeline
 *
 * Designed for easy modification — all sections are generated by
 * separate functions that can be tweaked independently.
 *
 * Usage: node sync-content.mjs
 */

import { readFileSync, writeFileSync, copyFileSync, mkdirSync, rmSync, readdirSync, existsSync } from 'fs'
import { join, dirname, relative, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const VAULT_ROOT = join(__dirname, '..')
const CONTENT_DIR = join(__dirname, 'content')

const EXCLUDE_DIRS = new Set([
  '.obsidian', '.automation', '.automation-git', '.website', '.git',
  'node_modules', '00 Dashboard', '01 System', '02 Event Log',
  '80 Templates', '90 Data',
])

// ─── Category Definitions ───
// Easy to modify: add/remove/reorder categories here
const CATEGORIES = [
  { key: 'briefing', icon: '📰', label: 'Briefing', fullLabel: 'Morning Briefing', desc: '매일 발행. 글로벌 시장 동향, 시장 센티먼트, 테마 딥다이브.' },
  { key: 'scan', icon: '⚡', label: 'Scan', fullLabel: 'Inflection Scan', desc: '시장 변곡점 탐지. 구조적 변화 시그널 포착.' },
  { key: 'deal-sourcing', icon: '📊', label: 'Deal', fullLabel: 'Deal Analysis', desc: '투자 기회 발굴. 비대칭 업사이드 중심 스크리닝.' },
  { key: 'deep', icon: '🔬', label: 'Deep', fullLabel: 'Deep & Final Analysis', desc: '기업/섹터 심층 분석. 25-80페이지.' },
  { key: 'thesis', icon: '🎯', label: 'Thesis', fullLabel: 'Investment Thesis', desc: '핵심 투자 테시스. Kill Criteria, Conviction 추적.' },
  { key: '_other', icon: '📂', label: 'Archives', fullLabel: 'Insights & Archives', desc: '유튜브 분석, PDF 리서치, 미팅 노트, 아이디어 메모.' },
]
const KNOWN_KEYS = new Set(CATEGORIES.filter(c => c.key !== '_other').map(c => c.key))

// ─── Quotes (rotated each publish) ───
const QUOTES = [
  { text: "Spend each day trying to be a little wiser than you were when you woke up.", author: "Charlie Munger" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { text: "The four most dangerous words in investing are: 'This time it's different.'", author: "Sir John Templeton" },
  { text: "In the short run, the market is a voting machine but in the long run, it is a weighing machine.", author: "Benjamin Graham" },
  { text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
  { text: "Be fearful when others are greedy, and greedy when others are fearful.", author: "Warren Buffett" },
]

console.log(`📁 Vault: ${VAULT_ROOT}`)
console.log(`📁 Content: ${CONTENT_DIR}`)

// ─── Clean ───
if (existsSync(CONTENT_DIR)) rmSync(CONTENT_DIR, { recursive: true })
mkdirSync(CONTENT_DIR, { recursive: true })

// ─── Walk & Sync ───
function walkDir(dir) {
  const files = []
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name)
      if (entry.isDirectory()) {
        if (!EXCLUDE_DIRS.has(entry.name) && !entry.name.startsWith('.')) {
          files.push(...walkDir(full))
        }
      } else if (entry.name.endsWith('.md')) {
        files.push(full)
      }
    }
  } catch { /* skip */ }
  return files
}

function parseFrontmatter(path) {
  try {
    const content = readFileSync(path, 'utf-8')
    const head = content.slice(0, 3000)
    if (!head.startsWith('---')) return null
    const end = head.indexOf('---', 3)
    if (end === -1) return null
    const fm = head.slice(3, end)

    const isPublish =
      /^publish:\s*true/m.test(fm) ||
      /^publish:\s*"true"/m.test(fm) ||
      /^publish:\s*\n\s*-\s*"?true"?/m.test(fm)
    if (!isPublish) return null

    const type = fm.match(/^type:\s*(.+)/m)?.[1]?.trim() || ''
    const title = fm.match(/^title:\s*(.+)/m)?.[1]?.trim() || ''
    const date = fm.match(/^date:\s*(.+)/m)?.[1]?.trim() || ''

    // Extract first meaningful paragraph for excerpt
    const bodyStart = content.indexOf('---', 3) + 3
    const body = content.slice(bodyStart).trim()
    const excerpt = extractExcerpt(body, 150)

    return { type, title, date, excerpt }
  } catch { return null }
}

function extractExcerpt(body, maxLen) {
  // Skip frontmatter remnants, headings, empty lines, YAML
  const lines = body.split('\n')
  const textLines = []
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue
    if (trimmed.startsWith('#')) continue
    if (trimmed.startsWith('---')) continue
    if (trimmed.startsWith('>')) {
      // Blockquote — extract text
      const clean = trimmed.replace(/^>\s*\*?\*?/, '').replace(/\*?\*?\s*$/, '').trim()
      if (clean.length > 20) {
        textLines.push(clean)
      }
      continue
    }
    if (trimmed.startsWith('|')) continue // table
    if (trimmed.startsWith('- [')) continue // task/link list
    // Normal text
    const clean = trimmed
      .replace(/\[\[([^\]|]+)\|?([^\]]*)\]\]/g, '$2$1') // wikilinks
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // md links
      .replace(/[*_`]/g, '') // formatting
      .trim()
    if (clean.length > 20) {
      textLines.push(clean)
      if (textLines.join(' ').length >= maxLen) break
    }
  }
  const full = textLines.join(' ').slice(0, maxLen)
  return full.length >= maxLen ? full.slice(0, full.lastIndexOf(' ')) + '...' : full
}

// Sync files
const published = []
let copied = 0, skipped = 0

for (const file of walkDir(VAULT_ROOT)) {
  if (basename(file) === 'index.md' && dirname(file) === VAULT_ROOT) {
    skipped++
    continue
  }

  const meta = parseFrontmatter(file)
  if (meta) {
    const rel = relative(VAULT_ROOT, file)
    const target = join(CONTENT_DIR, rel)
    mkdirSync(dirname(target), { recursive: true })
    copyFileSync(file, target)
    console.log(`  ✅ ${rel}`)

    // Build Quartz-compatible path for links
    const quartzPath = rel
      .replace(/\\/g, '/')
      .replace(/\.md$/, '')
      .replace(/ /g, '-')

    published.push({
      relPath: rel.replace(/\\/g, '/'),
      quartzPath,
      filename: basename(file, '.md'),
      type: meta.type,
      title: meta.title,
      date: meta.date,
      excerpt: meta.excerpt,
    })
    copied++
  } else {
    skipped++
  }
}

// ─── Group by Category ───
const byType = {}
for (const p of published) {
  let key = p.type
  if (['deep-company', 'deep-research', 'final-company', 'final-research'].includes(key)) key = 'deep'
  if (['inflection-scan'].includes(key)) key = 'scan'
  if (!KNOWN_KEYS.has(key)) key = '_other'
  if (!byType[key]) byType[key] = []
  byType[key].push(p)
}

for (const key of Object.keys(byType)) {
  byType[key].sort((a, b) => b.date.localeCompare(a.date))
}

// All reports sorted by date (for timeline)
const allSorted = [...published].sort((a, b) => b.date.localeCompare(a.date))

// ─── Generate Index.md ───

// Pick quote (rotate by day of year)
const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000)
const quote = QUOTES[dayOfYear % QUOTES.length]

// Featured report (most recent)
const featured = allSorted[0] || null

// Category icon lookup
const catLookup = {}
for (const c of CATEGORIES) catLookup[c.key] = c

let index = `---
title: Star Research
publish: true
cssclasses:
  - homepage
---

<div class="hero">
<div class="hero-ornament">── ✦ ──</div>

# STAR RESEARCH

<p class="hero-tagline">Investment Intelligence Platform</p>

<div class="hero-ornament">── ✦ ──</div>

<p class="hero-quote">"${quote.text}"<br/><span style="color:var(--gray);font-size:0.85em">— ${quote.author}</span></p>

</div>

---

`

// Featured section
if (featured) {
  const cat = catLookup[
    ['deep-company','deep-research','final-company','final-research'].includes(featured.type) ? 'deep' :
    ['inflection-scan'].includes(featured.type) ? 'scan' :
    KNOWN_KEYS.has(featured.type) ? featured.type : '_other'
  ] || catLookup['_other']

  index += `<div class="section-label">LATEST</div>

<div class="featured-card">

<span class="featured-badge">${cat.icon} ${cat.fullLabel.toUpperCase()}</span>

### [[${featured.filename}|${featured.title || featured.filename}]]

${featured.excerpt ? `${featured.excerpt}` : ''}

<span class="featured-meta">📅 ${featured.date}${featured.excerpt ? '  ·  📖 읽기' : ''}</span>

</div>

---

`
}

// Browse section
index += `<div class="section-label">BROWSE</div>

<div class="category-grid">
`

for (const cat of CATEGORIES) {
  const count = (byType[cat.key] || []).length
  index += `<div class="category-card">
<span class="category-icon">${cat.icon}</span>
<span class="category-count">${count}</span>
<span class="category-name">${cat.label}</span>
</div>
`
}

index += `</div>

---

`

// Recent section (timeline)
if (allSorted.length > 0) {
  index += `<div class="section-label">RECENT</div>

<div class="recent-list">
`

  for (const item of allSorted.slice(0, 20)) {
    let key = item.type
    if (['deep-company','deep-research','final-company','final-research'].includes(key)) key = 'deep'
    if (['inflection-scan'].includes(key)) key = 'scan'
    if (!KNOWN_KEYS.has(key)) key = '_other'
    const cat = catLookup[key] || catLookup['_other']
    const shortDate = item.date.slice(5) // MM-DD

    index += `<a class="recent-item" href="${item.quartzPath}">
<span class="recent-date">${shortDate}</span>
<span class="recent-badge">${cat.icon}</span>
<span class="recent-title">${item.title || item.filename}</span>
</a>
`
  }

  index += `</div>

---

`
}

// Footer quote
index += `<div style="text-align:center;opacity:0.3;font-size:0.8em;padding:16px 0">
Built with conviction.
</div>
`

writeFileSync(join(CONTENT_DIR, 'index.md'), index, 'utf-8')
console.log(`  📄 index.md 자동 생성 (${published.length}개 리포트)`)
console.log(`\n✅ Sync complete: ${copied} published, ${skipped} skipped`)
