/**
 * Content Sync & Homepage Generator
 * ═══════════════════════════════════
 * 1. Syncs publish:true notes from Obsidian vault → Quartz content/
 * 2. Auto-generates a beautiful index.md homepage with:
 *    - Hero section
 *    - Featured (latest) report card with excerpt
 *    - Category grid with counts
 *    - Recent reports timeline
 *
 * Designed for easy modification — all sections are generated by
 * separate functions that can be tweaked independently.
 *
 * Usage: node sync-content.mjs
 */

import { readFileSync, writeFileSync, copyFileSync, mkdirSync, rmSync, readdirSync, existsSync } from 'fs'
import { join, dirname, relative, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const VAULT_ROOT = join(__dirname, '..')
const CONTENT_DIR = join(__dirname, 'content')

const EXCLUDE_DIRS = new Set([
  '.obsidian', '.automation', '.automation-git', '.website', '.git',
  'node_modules', '00 Dashboard', '01 System', '02 Event Log',
  '80 Templates', '90 Data',
])

// ─── Category Definitions ───
// Easy to modify: add/remove/reorder categories here
const CATEGORIES = [
  { key: 'briefing', icon: '📰', label: 'Briefing', fullLabel: 'Morning Briefing', desc: '매일 발행. 글로벌 시장 동향, 시장 센티먼트, 테마 딥다이브.' },
  { key: 'scan', icon: '⚡', label: 'Scan', fullLabel: 'Inflection Scan', desc: '시장 변곡점 탐지. 구조적 변화 시그널 포착.' },
  { key: 'deal-sourcing', icon: '📊', label: 'Deal', fullLabel: 'Deal Analysis', desc: '투자 기회 발굴. 비대칭 업사이드 중심 스크리닝.' },
  { key: 'deep', icon: '🔬', label: 'Deep', fullLabel: 'Deep & Final Analysis', desc: '기업/섹터 심층 분석. 25-80페이지.' },
  { key: 'thesis', icon: '🎯', label: 'Thesis', fullLabel: 'Investment Thesis', desc: '핵심 투자 테시스. Kill Criteria, Conviction 추적.' },
  { key: '_other', icon: '📂', label: 'Archives', fullLabel: 'Insights & Archives', desc: '유튜브 분석, PDF 리서치, 미팅 노트, 아이디어 메모.' },
]
const KNOWN_KEYS = new Set(CATEGORIES.filter(c => c.key !== '_other').map(c => c.key))

// ─── Quotes (rotated each publish) ───
// ─── Quotes (rotated daily) ───
const QUOTES = [
  { text: "Spend each day trying to be a little wiser than you were when you woke up.", author: "Charlie Munger" },
  { text: "The big money is not in the buying and selling, but in the waiting.", author: "Charlie Munger" },
  { text: "Invert, always invert.", author: "Charlie Munger" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
  { text: "Be fearful when others are greedy, and greedy when others are fearful.", author: "Warren Buffett" },
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { text: "In the short run, the market is a voting machine but in the long run, it is a weighing machine.", author: "Benjamin Graham" },
  { text: "The investor's chief problem — and even his worst enemy — is likely to be himself.", author: "Benjamin Graham" },
  { text: "The most important thing is being attentive to cycles. Everything is cyclical.", author: "Howard Marks" },
  { text: "You can't predict. You can prepare.", author: "Howard Marks" },
  { text: "Know what you own, and know why you own it.", author: "Peter Lynch" },
  { text: "The key to making money in stocks is not to get scared out of them.", author: "Peter Lynch" },
  { text: "It's not whether you're right or wrong, but how much money you make when you're right and how much you lose when you're wrong.", author: "George Soros" },
  { text: "The four most dangerous words in investing are: 'This time it's different.'", author: "Sir John Templeton" },
  { text: "Bull markets are born on pessimism, grow on skepticism, mature on optimism, and die on euphoria.", author: "Sir John Templeton" },
  { text: "He who lives by the crystal ball will eat shattered glass.", author: "Ray Dalio" },
  { text: "The stock market is the story of cycles and of the human behavior that is responsible for overreactions in both directions.", author: "Seth Klarman" },
  { text: "The three most harmful addictions are heroin, carbohydrates, and a monthly salary.", author: "Nassim Taleb" },
  { text: "There is nothing new in Wall Street. There can't be because speculation is as old as the hills.", author: "Jesse Livermore" },
]

console.log(`📁 Vault: ${VAULT_ROOT}`)
console.log(`📁 Content: ${CONTENT_DIR}`)

// ─── Clean ───
if (existsSync(CONTENT_DIR)) rmSync(CONTENT_DIR, { recursive: true })
mkdirSync(CONTENT_DIR, { recursive: true })

// ─── Walk & Sync ───
function walkDir(dir) {
  const files = []
  try {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name)
      if (entry.isDirectory()) {
        if (!EXCLUDE_DIRS.has(entry.name) && !entry.name.startsWith('.')) {
          files.push(...walkDir(full))
        }
      } else if (entry.name.endsWith('.md')) {
        files.push(full)
      }
    }
  } catch { /* skip */ }
  return files
}

function parseFrontmatter(path) {
  try {
    const content = readFileSync(path, 'utf-8')
    const head = content.slice(0, 3000)
    if (!head.startsWith('---')) return null
    const end = head.indexOf('---', 3)
    if (end === -1) return null
    const fm = head.slice(3, end)

    const isPublish =
      /^publish:\s*true/m.test(fm) ||
      /^publish:\s*"true"/m.test(fm) ||
      /^publish:\s*\n\s*-\s*"?true"?/m.test(fm)
    if (!isPublish) return null

    const type = fm.match(/^type:\s*(.+)/m)?.[1]?.trim() || ''
    const title = fm.match(/^title:\s*(.+)/m)?.[1]?.trim() || ''
    const date = fm.match(/^date:\s*(.+)/m)?.[1]?.trim() || ''
    const created = fm.match(/^created:\s*(.+)/m)?.[1]?.trim() || ''
    // Extract time from created (e.g. "2026-03-26 18:24" → "18:24")
    const createdTime = created.match(/\d{2}:\d{2}/)?.[0] || ''

    // Extract first meaningful paragraph for excerpt
    const bodyStart = content.indexOf('---', 3) + 3
    const body = content.slice(bodyStart).trim()
    const excerpt = extractExcerpt(body, 150)

    return { type, title, date, createdTime, excerpt }
  } catch { return null }
}

function extractExcerpt(body, maxLen) {
  // Skip frontmatter remnants, headings, empty lines, YAML
  const lines = body.split('\n')
  const textLines = []
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue
    if (trimmed.startsWith('#')) continue
    if (trimmed.startsWith('---')) continue
    if (trimmed.startsWith('>')) {
      // Blockquote — extract text
      const clean = trimmed.replace(/^>\s*\*?\*?/, '').replace(/\*?\*?\s*$/, '').trim()
      if (clean.length > 20) {
        textLines.push(clean)
      }
      continue
    }
    if (trimmed.startsWith('|')) continue // table
    if (trimmed.startsWith('- [')) continue // task/link list
    // Normal text
    const clean = trimmed
      .replace(/\[\[([^\]|]+)\|?([^\]]*)\]\]/g, '$2$1') // wikilinks
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // md links
      .replace(/[*_`]/g, '') // formatting
      .trim()
    if (clean.length > 20) {
      textLines.push(clean)
      if (textLines.join(' ').length >= maxLen) break
    }
  }
  const full = textLines.join(' ').slice(0, maxLen)
  return full.length >= maxLen ? full.slice(0, full.lastIndexOf(' ')) + '...' : full
}

// Sync files
const published = []
let copied = 0, skipped = 0

for (const file of walkDir(VAULT_ROOT)) {
  if (basename(file) === 'index.md' && dirname(file) === VAULT_ROOT) {
    skipped++
    continue
  }

  const meta = parseFrontmatter(file)
  if (meta) {
    const rel = relative(VAULT_ROOT, file)
    const target = join(CONTENT_DIR, rel)
    mkdirSync(dirname(target), { recursive: true })
    copyFileSync(file, target)
    console.log(`  ✅ ${rel}`)

    // Build Quartz-compatible path for links
    const quartzPath = rel
      .replace(/\\/g, '/')
      .replace(/\.md$/, '')
      .replace(/ /g, '-')

    // Display title: use frontmatter title as-is
    // New files: title already includes time (e.g. "Morning Brief 2026-03-26 18:24")
    // Old files: title without time (e.g. "Morning Brief 2026-03-26") → append from created
    let displayTitle = meta.title
    const hasTime = /\d{2}:\d{2}\s*$/.test(meta.title)
    if (!hasTime && meta.createdTime) {
      displayTitle = `${meta.title} ${meta.createdTime}`
    }

    published.push({
      relPath: rel.replace(/\\/g, '/'),
      quartzPath,
      filename: basename(file, '.md'),
      type: meta.type,
      title: meta.title,
      displayTitle,
      date: meta.date,
      createdTime: meta.createdTime,
      excerpt: meta.excerpt,
    })
    copied++
  } else {
    skipped++
  }
}

// ─── Group by Category ───
const byType = {}
for (const p of published) {
  let key = p.type
  if (['deep-company', 'deep-research', 'final-company', 'final-research'].includes(key)) key = 'deep'
  if (['inflection-scan'].includes(key)) key = 'scan'
  if (!KNOWN_KEYS.has(key)) key = '_other'
  if (!byType[key]) byType[key] = []
  byType[key].push(p)
}

for (const key of Object.keys(byType)) {
  byType[key].sort((a, b) => b.date.localeCompare(a.date))
}

// All reports sorted by date (for timeline)
const allSorted = [...published].sort((a, b) => b.date.localeCompare(a.date))

// ─── Generate Index.md ───

// Pick quote (rotate by day of year)
// Rotate by day of year
const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000)
const quote = QUOTES[dayOfYear % QUOTES.length]

// Featured report (most recent)
const featured = allSorted[0] || null

// Category icon lookup
const catLookup = {}
for (const c of CATEGORIES) catLookup[c.key] = c

// ─── Helper: resolve category key ───
function resolveCatKey(type) {
  if (['deep-company','deep-research','final-company','final-research'].includes(type)) return 'deep'
  if (['inflection-scan'].includes(type)) return 'scan'
  if (!KNOWN_KEYS.has(type)) return '_other'
  return type
}

let index = `---
title: Star Research
publish: true
cssclasses:
  - homepage
---

<div class="hero-compact">
<span class="hero-brand">✦ STAR RESEARCH</span>
<span class="hero-divider">—</span>
<span class="hero-quote-inline">"${quote.text}" <em>— ${quote.author}</em></span>
</div>

<div class="category-pills">
`

// Category pills (horizontal row)
for (const cat of CATEGORIES) {
  const count = (byType[cat.key] || []).length
  if (count > 0) {
    index += `<a class="pill" href="categories/${cat.key}">${cat.icon} ${cat.label} <span class="pill-count">${count}</span></a> `
  } else {
    index += `<span class="pill pill-empty">${cat.icon} ${cat.label}</span> `
  }
}

index += `<a class="pill pill-about" href="about">ℹ️ About</a>
</div>

---

`

// Content feed (up to 10 latest, as rich cards)
const feedItems = allSorted.slice(0, 10)

if (feedItems.length > 0) {
  for (const item of feedItems) {
    const catKey = resolveCatKey(item.type)
    const cat = catLookup[catKey] || catLookup['_other']

    index += `<a class="feed-card" href="${item.quartzPath}">
<div class="feed-header">
<span class="feed-badge">${cat.icon} ${cat.label.toUpperCase()}</span>
<span class="feed-date">${item.date}</span>
</div>
<div class="feed-title">${item.displayTitle || item.filename}</div>
${item.excerpt ? `<div class="feed-excerpt">${item.excerpt}</div>` : ''}
</a>

`
  }
}

if (feedItems.length === 0) {
  index += `<div style="text-align:center;color:var(--gray);padding:48px 0">아직 게시된 리포트가 없습니다.</div>\n\n`
}

// Footer
index += `<div style="text-align:center;opacity:0.25;font-size:0.8em;padding:24px 0">
Built with conviction.
</div>
`

writeFileSync(join(CONTENT_DIR, 'index.md'), index, 'utf-8')
console.log(`  📄 index.md 자동 생성 (${published.length}개 리포트)`)

// ─── Generate Category Listing Pages ───
const categoriesDir = join(CONTENT_DIR, 'categories')
mkdirSync(categoriesDir, { recursive: true })

let catPagesCreated = 0
for (const cat of CATEGORIES) {
  const items = byType[cat.key] || []
  if (items.length === 0) continue

  let page = `---
title: ${cat.icon} ${cat.fullLabel}
publish: true
---

# ${cat.icon} ${cat.fullLabel}

> ${cat.desc}

**${items.length}개 리포트** | [← 홈으로 돌아가기](/)

---

<div class="recent-list">
`

  for (const item of items) {
    page += `<a class="recent-item" href="/${item.quartzPath}">
<span class="recent-date">${item.date}</span>
<span class="recent-title">${item.displayTitle || item.filename}</span>
</a>
`
  }

  page += `</div>
`

  writeFileSync(join(categoriesDir, `${cat.key}.md`), page, 'utf-8')
  catPagesCreated++
  console.log(`  📂 categories/${cat.key}.md (${items.length}개)`)
}

// ─── Generate About Page ───
const aboutPage = `---
title: About Star Research
publish: true
---

# About Star Research

> AI 기반 투자 리서치 시스템. 데이터 수집부터 분석, 검증, 테시스 생성까지 자동화된 파이프라인으로 일관된 품질의 투자 인텔리전스를 생성합니다.

[← 홈으로 돌아가기](/)

---

## 리서치 파이프라인

\`\`\`
⚡ Scan ──→ 📊 Deal ──→ 🔬 Deep ──→ 📋 Final ──→ 🎯 Thesis
변곡점 탐지   기회 발굴    심층 분석    최종 판단    투자 테시스
\`\`\`

**📰 Morning Briefing** ← 매일 시장 전체를 관통하는 일일 인텔리전스

**📂 Insights & Archives** ← 유튜브, PDF, 미팅 노트 등 기타 리서치

---

## 📰 Morning Briefing

매일 07:30 자동 발행. 글로벌 시장을 한눈에 파악하는 일일 브리핑.

- **시장 스냅샷**: 주요 지수, 매크로, 원자재, 크립토 — Yahoo Finance 실시간 데이터
- **시장 센티먼트 & 방향성**: Risk-On/Off 비율, 시장 국면 진단
- **오버나이트 핵심 이벤트 Top 5**: So What 분석 + 크로스 임팩트
- **테마 딥다이브**: 매일 하나의 구조적 시장 테마를 깊이 분석
- **Must-Read 3선**: RSS 큐레이션 + URL 검증된 실제 기사 추천
- **투자 레슨**: 역사적 유사 사례 연결

> 빈도: **매일** | 분량: 4-6페이지

---

## ⚡ Inflection Scan

시장의 구조적 변곡점을 탐지하는 시그널 스캐너.

- 8개 시그널 소스 + RSS + 소셜 미디어 + 이벤트 캘린더
- AI가 변곡점 후보를 추출하고, High Conviction만 보고서로 생성
- Deal Analysis와 Deep Analysis의 시작점 역할

> 빈도: **수시** | 분량: 3-5페이지 | 비용: ~$0.20

---

## 📊 Deal Analysis

투자 기회 발굴과 초기 스크리닝.

- 뉴스, 재무 데이터, 애널리스트 의견을 종합
- 비대칭 업사이드 중심 평가
- BUY / WATCH / PASS 판정과 근거 제시

> 빈도: **수시** | 분량: 10-15페이지 | 비용: ~$0.50

---

## 🔬 Deep & Final Analysis

기업 또는 섹터의 심층 분석. 투자 의사결정 직전 최종 점검용.

- **Deep (25-35p)**: 비즈니스 모델, 경쟁 우위, 재무 해석, 시나리오 분석
- **Final (50-80p)**: 21개 쿼리 + 재무 + 3-pass 검증. 최종 판단 보고서
- Opus 급 AI 모델이 다중 섹션을 독립 분석 후 통합

> 빈도: **주 1-2회** | 분량: 25-80페이지 | 비용: $0.80-6.50

---

## 🎯 Investment Thesis

종목별 핵심 투자 테시스. 모든 분석의 결론.

- 기존 리포트를 종합하여 핵심 투자 논리 정리
- Kill Criteria (테시스 폐기 조건) 명시
- Conviction 추적 및 정기 리뷰
- 시장 변화에 따른 테시스 진화 기록

> 빈도: **종목별** | 분량: 5-10페이지

---

## 📂 Insights & Archives

위 카테고리에 해당하지 않는 모든 리서치 자료.

- 유튜브 영상 분석
- PDF 리포트 정리
- 미팅 노트
- 아이디어 메모
- 기타 리서치

---

## 시스템 특징

| 특징 | 설명 |
|------|------|
| **할루시네이션 방지** | 시장 데이터는 Yahoo Finance 직접 수집, Must-Read URL은 HTTP 검증 |
| **자동화** | 매일 07:30 모닝 브리프 자동 생성, 텔레그램 명령어로 즉시 분석 |
| **동시 실행** | 최대 3개 분석을 동시에 실행 (Job Queue 시스템) |
| **예측 추적** | 리포트의 투자 예측을 자동 추출하고 실제 결과와 비교 |
| **자기 개선** | 예측 정확도, 비용, 피드백을 분석하여 시스템 지속 개선 |
`

writeFileSync(join(CONTENT_DIR, 'about.md'), aboutPage, 'utf-8')
console.log(`  📄 about.md 생성`)

console.log(`\n✅ Sync complete: ${copied} published, ${catPagesCreated} category pages, ${skipped} skipped`)
